
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let strings = new LocalizedStrings({
    
    //Language english
    en: {
        login: "Login",
        sign: "Sign up",
        entrfn:'Enter your first name',
        entrln:'Enter your last name',
        entremail:'Enter your email',
        entrpn:'Enter your phone no.',
        entrpass:'Enter your password',
        email: "Email",
        password: "Password",
        fp: 'Forget Password',
        fn: 'First name',
        ln: 'Last name',
        pn: 'Phone No.',
        service: 'Services',
        vd: 'View details',
        sub: 'Submit',
        al: 'Already have an account?',
        ln: 'Login here',
        up: 'Upload profile picture',
        ok: 'Ok',
        noti:'Notifications',
        notiDe:'Notification Detail',
        prod:'Products',
        prodDe:'Product Detail',
        fprod:'Favourite Products',
        userpr:'User Profile',
        editprofile:'Edit Profile',
        cusId:'Customer id',
        name:'Name',
        mydetailer:'My Detailers',
        detailerlist:'Detailer List',
        mycars:'My Cars',
        addcar:"Add Car",
        editcar:"Edit Car",
        setting:'Settings',
        changepassword:'Change Password',
        oldpassword:'Old Password',
        newpassword:'New Password',
        entroldpass:'',
        logout:'Logout'
    },

    // Language German
    de: {
        login: "s'identifier",
        sign: "s'inscrire",
        entrfn:'Geben Sie Ihren Vornamen ein',
        entrln:'Geben Sie Ihren Nachnamen ein',
        entremail:'Geben sie ihre E-Mail Adresse ein',
        entrpn:'Geben Sie Ihre Telefonnummer ein.',
        entrpass:'Geben Sie Ihr Passwort ein',
        email: "Email",
        password: "Passwort",
        fp: 'Passwort vergessen',
        fn: 'Vorname',
        ln: 'Nachname',
        pn: 'Telefon-Nr.',
        service: 'Services',
        vd: 'Im Detail sehen',
        sub: 'einreichen',
        al: "Sie haben bereits ein Konto?",
        ln: 'Hier anmelden',
        up: 'Profilbild hochladen',
        ok: 'Ok',
        noti:'Benachrichtigungen',
        notiDe:'Benachrichtigungsdetail',
        prod:'Produkte',
        prodDe:'Produktdetail',
        fprod:'Lieblingsprodukte',
        userpr:'Benutzerprofil',
        editprofile:'Profil bearbeiten',
        cusId:'Kundennummer',
        name:'Name',
        mydetailer:'Meine Detailer',
        detailerlist:'Detaillierte Liste',
        mycars:'Meine Autos',
        addcar:"Auto hinzufügen",
        editcar:'Auto bearbeiten',
        setting:'die Einstellungen',
        changepassword:'ändere das Passwort',
        oldpassword:'Altes Passwort',
        newpassword:'Neues Kennwort',
        entroldpass:'',
        logout:'Ausloggen'

    },

    // Language French
    fr: {
        login: "accesso",
        sign: "Iscriviti",
        entrfn:'Entrez votre prénom',
        entrln:'entrez votre nom de famille',
        entremail:'Entrer votre Email',
        entrpn:'Entrez votre numéro de téléphone.',
        entrpass:'Tapez votre mot de passe',
        email: "Email",
        password: "mot de passe",
        fp: 'mot de passe oublié',
        fn: 'Prénom',
        ln: 'nom de famille',
        pn: 'Pas de téléphone.',
        service: 'Plan de services',
        vd: 'voir les détails',
        sub: 'soumettre',
        al: 'Vous avez déjà un compte?',
        ln: 'Connectez-vous ici',
        up: 'télécharger une photo de profil',
        ok: 'Daccord',
        noti:'Notifications',
        notiDe:'Détail de la notification',
        prod:'Des produits',
        prodDe:'Les détails du produit',
        fprod:'Produits préférés',
        userpr:'Profil de l utilisateur',
        editprofile:'Editer le profil',
        cusId:'N ° de client',
        name:'Nom',
        mydetailer:'Mes détaillants',
        detailerlist:'Liste des détaillants',
        mycars:'Mes voitures',
        addcar:'Ajouter une voiture',
        editcar:'Modifier la voiture',
        setting:'Paramètres',
        changepassword:'changer le mot de passe',
        oldpassword:'ancien mot de passe',
        newpassword:'nouveau mot de passe',
        entroldpass:'',
        logout:'Se déconnecter',

    },

    // Language Dutch
    nl: {
        login: "Log in",
        sign: "inschrijven",
        entrfn:'Vul uw voornaam in',
        entrln:'voer uw achternaam in',
        entremail:'Voer uw e-mailadres in',
        entrpn:'Voer uw telefoonnummer in.',
        entrpass:'Voer uw wachtwoord in',
        email: "E-mail",
        password: "Wachtwoord",
        fp: 'wachtwoord vergeten',
        fn: 'Voornaam',
        ln: 'achternaam',
        pn: 'telefoon nr.',
        service: 'Diensten',
        vd: 'Bekijk details',
        sub: 'Verzenden',
        al: 'Heeft u al een account?',
        ln: 'achternaam',
        up: 'Profielfoto uploaden',
        ok: 'OK',
        noti:'Kennisgevingen',
        notiDe:'Kennisgevingsdetail',
        prod:'Producten',
        prodDe:'Product detail',
        fprod:'Favoriete producten',
        userpr:'Gebruikersprofiel',
        editprofile:'Bewerk profiel',
        cusId:'Klanten ID',
        name:'Naam',
        mydetailer:'Mijn detailers',
        detailerlist:'Lijst met details',
        mycars:'Mijn auto s',
        addcar:'Auto toevoegen',
        editcar:'Auto bewerken',
        setting:'Instellingen',
        changepassword:'wachtwoord wijzigen',
        oldpassword:'Oud Wachtwoord',
        newpassword:'nieuw paswoord',
        entroldpass:'',
        logout:'Uitloggen',
        
    },

     // Language Poland
    pl: {
        login: "Zaloguj sie",
        sign: "Zapisz się",
        entrfn:'Wpisz swoje imię',
        entrln:'wprowadź swoje nazwisko',
        entremail:'Wprowadź swój email',
        entrpn:'Wprowadź numer telefonu',
        entrpass:'Wprowadź hasło',
        email: "E-mail",
        password: "Hasło",
        fp: 'zapomnij hasło',
        fn: 'Imię',
        ln: 'nazwisko',
        pn: 'nr telefonu.',
        service: 'Usługi',
        vd: 'Pokaż szczegóły',
        sub: 'Zatwierdź',
        al: 'Posiadasz już konto?',
        ln: 'Zaloguj się tutaj',
        up: 'Prześlij zdjęcie profilowe',
        ok: 'dobrze',
        noti:'Powiadomienia',
        notiDe:'Szczegóły powiadomienia',
        prod:'Produkty',
        prodDe:'Szczegóły produktu',
        fprod:'Ulubione produkty',
        userpr:'Profil użytkownika',
        editprofile:'Edytuj profil',
        cusId:'Identyfikator klienta',
        name:'Imię',
        mydetailer:'Moi Detailerzy',
        detailerlist:'Lista szczegółów',
        mycars:'Moje samochody',
        addcar:'Dodaj samochód',
        editcar:'Edytuj samochód',
        setting:'Ustawienia',
        changepassword:'Zmień hasło',
        oldpassword:'Stare hasło',
        newpassword:'nowe hasło',
        entroldpass:'',
        logout:'Wyloguj'
    },

     // Language Russian
    cs: {
        login: "Авторизоваться",
        sign: "зарегистрироваться",
        entrfn:'Введите свое имя',
        entrln:'введите свою фамилию',
        entremail:'Введите адрес электронной почты',
        entrpn:'Введите номер телефона',
        entrpass:'Введите ваш пароль',
        email: "Эл. адрес",
        password: "пароль",
        fp: 'забыть пароль',
        fn: 'Имя',
        ln: 'Фамилия',
        pn: 'телефонный номер.',
        service: 'Сервисы',
        vd: 'Посмотреть детали',
        sub: 'Отправить',
        al: 'Уже есть аккаунт?',
        ln: 'Войти здесь',
        up: 'Загрузить изображение профиля',
        ok: 'хорошо',
        noti:'Уведомления',
        notiDe:'Деталь уведомления',
        prod:'Товары',
        prodDe:'Информация о продукте',
        fprod:'Любимые продукты',
        userpr:'Профиль пользователя',
        editprofile:'Редактировать профиль',
        cusId:'Пользовательский ИД',
        name:'название',
        mydetailer:'Мои подробности',
        detailerlist:'Список деталей',
        mycars:'Мои автомобили',
        addcar:'Добавить автомобиль',
        editcar:'Редактировать автомобиль',
        setting:'настройки',
        changepassword:'сменить пароль',
        oldpassword:'Прежний пароль',
        newpassword:'Новый пароль',
        entroldpass:'',
        logout:'Выйти'
    },

    //   Language Spanish
    es: {
        login: "Iniciar sesión",
        sign: "Regístrate",
        entrfn:'ponga su primer nombre',
        entrln:'ingresa tu apellido',
        entremail:'Introduce tu correo electrónico',
        entrpn:'Ingrese su número de teléfono.',
        entrpass:'Ingresa tu contraseña',
        email: "correo electrónico",
        password: "Contraseña",
        fp: 'contraseña olvidada',
        fn: 'nombre de pila',
        ln: 'apellido',
        pn: 'telefono no.',
        service: 'Servicios',
        vd: 'Ver detalles',
        sub: 'Enviar',
        al: '¿Ya tienes una cuenta?',
        ln: 'Entre aquí',
        up: 'Subir foto de perfil',
        ok: 'Okay',
        noti:'Notificaciones',
        notiDe:'Detalle de notificaciones',
        prod:'Productos',
        prodDe:'Detalle del producto',
        fprod:'Productos favoritos',
        userpr:'Perfil del usuario',
        editprofile:'Editar perfil',
        cusId:'Identificación del cliente',
        name:'Nombre',
        mydetailer:'Mis detailers',
        detailerlist:'Lista de detallistas',
        mycars:'Mis carros',
        addcar:'Añadir coche',
        editcar:'Editar coche',
        setting:'Configuraciones',
        changepassword:'Cambia la contraseña',
        oldpassword:'Contraseña anterior',
        newpassword:'Nueva contraseña',
        logout:'Cerrar sesión'
    },
});
